#!/bin/bash

source /d/applications/anaconda/etc/profile.d/conda.sh
conda activate sam

#cd /e/Py_codes/LVM_Comparision/Feature_Similarity_paper_report/Gabor_test/test || return

#python stlpips_test_on_gabors_different_rho_contour_plot_aim.py
#python stlpips_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python stlpips_test_on_gabors_different_rho_contour_plot_YV_aim.py

#python dino_test_on_gabors_different_area_contour_plot_aim.py
#python dino_test_on_gabors_different_L_b_contour_plot_aim.py
#python dino_test_on_gabors_different_rho_contour_plot_aim.py
#python dino_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python dino_test_on_gabors_different_rho_contour_plot_YV_aim.py
#
#python dinov2_test_on_gabors_different_area_contour_plot_aim.py
#python dinov2_test_on_gabors_different_L_b_contour_plot_aim.py
#python dinov2_test_on_gabors_different_rho_contour_plot_aim.py
#python dinov2_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python dinov2_test_on_gabors_different_rho_contour_plot_YV_aim.py

#python openclip_test_on_gabors_different_area_contour_plot_aim.py
#python openclip_test_on_gabors_different_L_b_contour_plot_aim.py
#python openclip_test_on_gabors_different_rho_contour_plot_aim.py
#python openclip_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python openclip_test_on_gabors_different_rho_contour_plot_YV_aim.py

#python sam2_test_on_gabors_different_area_contour_plot_aim.py
#python sam2_test_on_gabors_different_L_b_contour_plot_aim.py
#python sam2_test_on_gabors_different_rho_contour_plot_aim.py
#python sam2_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python sam2_test_on_gabors_different_rho_contour_plot_YV_aim.py

#python mae_test_on_gabors_different_area_contour_plot_aim.py
#python mae_test_on_gabors_different_L_b_contour_plot_aim.py
#python mae_test_on_gabors_different_rho_contour_plot_aim.py
#python mae_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python mae_test_on_gabors_different_rho_contour_plot_YV_aim.py
#
#python vae_test_on_gabors_different_area_contour_plot_aim.py
#python vae_test_on_gabors_different_L_b_contour_plot_aim.py
#python vae_test_on_gabors_different_rho_contour_plot_aim.py
#python vae_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python vae_test_on_gabors_different_rho_contour_plot_YV_aim.py

#python sam_test_on_gabors_different_area_contour_plot.py
#python sam_test_on_gabors_different_L_b_contour_plot.py
#python sam_test_on_gabors_different_rho_contour_plot.py
#python sam_test_on_gabors_different_rho_contour_plot_RG.py
#python sam_test_on_gabors_different_rho_contour_plot_YV.py

#python mae_test_on_gabors_different_area_contour_plot.py
#python mae_test_on_gabors_different_L_b_contour_plot.py
#python mae_test_on_gabors_different_rho_contour_plot.py
#python mae_test_on_gabors_different_rho_contour_plot_RG.py
#python mae_test_on_gabors_different_rho_contour_plot_YV.py
#
#python plot_mae_feature_similarity_different_area_contour.py
#python plot_mae_feature_similarity_different_L_b_contour.py
#python plot_mae_feature_similarity_different_rho_contour.py
#python plot_mae_feature_similarity_different_rho_contour_RG.py
#python plot_mae_feature_similarity_different_rho_contour_YV.py

#python sam2_test_on_gabors_different_area_contour_plot.py
#python sam2_test_on_gabors_different_L_b_contour_plot.py
#python sam2_test_on_gabors_different_rho_contour_plot.py
#python sam2_test_on_gabors_different_rho_contour_plot_RG.py
#python sam2_test_on_gabors_different_rho_contour_plot_YV.py

#python plot_sam_feature_similarity_different_area_contour.py
#python plot_sam_feature_similarity_different_L_b_contour.py
#python plot_sam_feature_similarity_different_rho_contour.py
#python plot_sam_feature_similarity_different_rho_contour_RG.py
#python plot_sam_feature_similarity_different_rho_contour_YV.py

#cd /e/Py_codes/LVM_Comparision/Feature_Similarity_paper_report/Contrast_masking_test || return
#python baseline_test_on_contrast_masking_different_c_contour_plot.py
#python dino_test_on_contrast_masking_different_c_contour_plot.py
#python dinov2_test_on_contrast_masking_different_c_contour_plot.py
#python openclip_test_on_contrast_masking_different_c_contour_plot.py
#python sam_test_on_contrast_masking_different_c_contour_plot.py
#python mae_test_on_contrast_masking_different_c_contour_plot.py
#python vae_test_on_contrast_masking_different_c_contour_plot.py
#python lpips_test_on_contrast_masking_different_c_contour_plot.py
#python stlpips_test_on_contrast_masking_different_c_contour_plot.py
#python cvvdp_test_on_contrast_masking_different_c_contour_plot.py
#
#python plot_baseline_feature_similarity_different_c_contour.py
#python plot_cvvdp_feature_similarity_different_c_contour.py
#python plot_dino_feature_similarity_different_c_contour.py
#python plot_dinov2_feature_similarity_different_c_contour.py
#python plot_lpips_feature_similarity_different_c_contour.py
#python plot_mae_feature_similarity_different_c_contour.py
#python plot_openclip_feature_similarity_different_c_contour.py
#python plot_sam_feature_similarity_different_c_contour.py
#python plot_stlpips_feature_similarity_different_c_contour.py
#python plot_vae_feature_similarity_different_c_contour.py

#
#cd /e/Py_codes/LVM_Comparision/Feature_Similarity_paper_report/Contrast_masking_band_limit_noise_test  || return
#python sam_test_on_contrast_masking_different_c_contour_plot.py
#python plot_sam_feature_similarity_different_c_contour.py

cd /e/Py_codes/LVM_Comparision/Feature_Similarity_paper_report/Contrast_masking_test_gabor_on_noise/test  || return
python dinov2_test_on_contrast_masking_different_c_contour_plot_aim.py
python openclip_test_on_contrast_masking_different_c_contour_plot_aim.py
python sam_test_on_contrast_masking_different_c_contour_plot_aim.py
python sam2_test_on_contrast_masking_different_c_contour_plot_aim.py
python mae_test_on_contrast_masking_different_c_contour_plot_aim.py
python vae_test_on_contrast_masking_different_c_contour_plot_aim.py
python lpips_test_on_contrast_masking_different_c_contour_plot_aim.py
python stlpips_test_on_contrast_masking_different_c_contour_plot_aim.py
python cvvdp_test_on_contrast_masking_different_c_contour_plot_aim.py

#python baseline_test_on_contrast_masking_different_c_contour_plot.py
#python dino_test_on_contrast_masking_different_c_contour_plot.py
#python dinov2_test_on_contrast_masking_different_c_contour_plot.py
#python openclip_test_on_contrast_masking_different_c_contour_plot.py
#python sam_test_on_contrast_masking_different_c_contour_plot.py
#python mae_test_on_contrast_masking_different_c_contour_plot.py
#python vae_test_on_contrast_masking_different_c_contour_plot.py
#python lpips_test_on_contrast_masking_different_c_contour_plot.py
#python stlpips_test_on_contrast_masking_different_c_contour_plot.py
#python cvvdp_test_on_contrast_masking_different_c_contour_plot.py

#python plot_baseline_feature_similarity_different_c_contour.py
#python plot_cvvdp_feature_similarity_different_c_contour.py
#python plot_dino_feature_similarity_different_c_contour.py
#python plot_dinov2_feature_similarity_different_c_contour.py
#python plot_lpips_feature_similarity_different_c_contour.py
#python plot_mae_feature_similarity_different_c_contour.py
#python plot_openclip_feature_similarity_different_c_contour.py
#python plot_sam_feature_similarity_different_c_contour.py
#python plot_stlpips_feature_similarity_different_c_contour.py
#python plot_vae_feature_similarity_different_c_contour.py


#
#cd /e/Py_codes/LVM_Comparision/Feature_Similarity_paper_report/Band_lim_noise_test  || return
#python sam2_test_on_band_lim_noise_different_rho_contour_plot.py
#python plot_sam_feature_similarity_different_rho_contour.py
#python mae_test_on_band_lim_noise_different_rho_contour_plot.py
#python plot_mae_feature_similarity_different_rho_contour.py

#cd /e/Py_codes/LVM_Comparision/Feature_Similarity_paper_report/Contrast_constancy/test  || return
#python baseline_test.py
#python cvvdp_test.py
#python dino_test.py
#python dinov2_test.py
#python mae_test.py
#python openclip_test.py
#python sam_test.py
#python sam2_test.py
#python vae_test.py
#python lpips_test.py
#python stlpips_test.py

#cd /e/Py_codes/LVM_Comparision/Feature_Similarity_paper_report/Contrast_constancy/plot  || return
#python sam_plot.py
#python sam2_plot.py
