#!/bin/bash

source /d/applications/anaconda/etc/profile.d/conda.sh
conda activate sam

cd /e/Py_codes/LVM_Comparision/Feature_Similarity_paper_report_50/Gabor_test/test || return
#python baseline_test_on_gabors_different_area_contour_plot.py
#python baseline_test_on_gabors_different_area_contour_plot_aim.py
#python baseline_test_on_gabors_different_L_b_contour_plot.py
#python baseline_test_on_gabors_different_L_b_contour_plot_aim.py
#python baseline_test_on_gabors_different_rho_contour_plot.py
#python baseline_test_on_gabors_different_rho_contour_plot_aim.py
#python baseline_test_on_gabors_different_rho_contour_plot_RG.py
#python baseline_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python baseline_test_on_gabors_different_rho_contour_plot_YV.py
#python baseline_test_on_gabors_different_rho_contour_plot_YV_aim.py

#python openclip_test_on_gabors_different_area_contour_plot.py
#python openclip_test_on_gabors_different_area_contour_plot_aim.py
python openclip_test_on_gabors_different_L_b_contour_plot.py
python openclip_test_on_gabors_different_L_b_contour_plot_aim.py
#python openclip_test_on_gabors_different_rho_contour_plot.py
#python openclip_test_on_gabors_different_rho_contour_plot_aim.py
#python openclip_test_on_gabors_different_rho_contour_plot_RG.py
#python openclip_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python openclip_test_on_gabors_different_rho_contour_plot_YV.py
#python openclip_test_on_gabors_different_rho_contour_plot_YV_aim.py
#
#python sam2_test_on_gabors_different_area_contour_plot.py
#python sam2_test_on_gabors_different_area_contour_plot_aim.py
#python sam2_test_on_gabors_different_L_b_contour_plot.py
#python sam2_test_on_gabors_different_L_b_contour_plot_aim.py
#python sam2_test_on_gabors_different_rho_contour_plot.py
#python sam2_test_on_gabors_different_rho_contour_plot_aim.py
#python sam2_test_on_gabors_different_rho_contour_plot_RG.py
#python sam2_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python sam2_test_on_gabors_different_rho_contour_plot_YV.py
#python sam2_test_on_gabors_different_rho_contour_plot_YV_aim.py
#
#python sam_test_on_gabors_different_area_contour_plot.py
#python sam_test_on_gabors_different_area_contour_plot_aim.py
#python sam_test_on_gabors_different_L_b_contour_plot.py
#python sam_test_on_gabors_different_L_b_contour_plot_aim.py
#python sam_test_on_gabors_different_rho_contour_plot.py
#python sam_test_on_gabors_different_rho_contour_plot_aim.py
#python sam_test_on_gabors_different_rho_contour_plot_RG.py
#python sam_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python sam_test_on_gabors_different_rho_contour_plot_YV.py
#python sam_test_on_gabors_different_rho_contour_plot_YV_aim.py
#
#python cvvdp_test_on_gabors_different_area_contour_plot.py
#python cvvdp_test_on_gabors_different_area_contour_plot_aim.py
#python cvvdp_test_on_gabors_different_L_b_contour_plot.py
#python cvvdp_test_on_gabors_different_L_b_contour_plot_aim.py
#python cvvdp_test_on_gabors_different_rho_contour_plot.py
#python cvvdp_test_on_gabors_different_rho_contour_plot_aim.py
#python cvvdp_test_on_gabors_different_rho_contour_plot_RG.py
#python cvvdp_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python cvvdp_test_on_gabors_different_rho_contour_plot_YV.py
#python cvvdp_test_on_gabors_different_rho_contour_plot_YV_aim.py
#
#python dino_test_on_gabors_different_area_contour_plot.py
#python dino_test_on_gabors_different_area_contour_plot_aim.py
#python dino_test_on_gabors_different_L_b_contour_plot.py
#python dino_test_on_gabors_different_L_b_contour_plot_aim.py
#python dino_test_on_gabors_different_rho_contour_plot.py
#python dino_test_on_gabors_different_rho_contour_plot_aim.py
#python dino_test_on_gabors_different_rho_contour_plot_RG.py
#python dino_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python dino_test_on_gabors_different_rho_contour_plot_YV.py
#python dino_test_on_gabors_different_rho_contour_plot_YV_aim.py
#
#python dinov2_test_on_gabors_different_area_contour_plot.py
#python dinov2_test_on_gabors_different_area_contour_plot_aim.py
#python dinov2_test_on_gabors_different_L_b_contour_plot.py
#python dinov2_test_on_gabors_different_L_b_contour_plot_aim.py
#python dinov2_test_on_gabors_different_rho_contour_plot.py
#python dinov2_test_on_gabors_different_rho_contour_plot_aim.py
#python dinov2_test_on_gabors_different_rho_contour_plot_RG.py
#python dinov2_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python dinov2_test_on_gabors_different_rho_contour_plot_YV.py
#python dinov2_test_on_gabors_different_rho_contour_plot_YV_aim.py
#
#python lpips_test_on_gabors_different_area_contour_plot.py
#python lpips_test_on_gabors_different_area_contour_plot_aim.py
#python lpips_test_on_gabors_different_L_b_contour_plot.py
#python lpips_test_on_gabors_different_L_b_contour_plot_aim.py
#python lpips_test_on_gabors_different_rho_contour_plot.py
#python lpips_test_on_gabors_different_rho_contour_plot_aim.py
#python lpips_test_on_gabors_different_rho_contour_plot_RG.py
#python lpips_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python lpips_test_on_gabors_different_rho_contour_plot_YV.py
#python lpips_test_on_gabors_different_rho_contour_plot_YV_aim.py
#
#python mae_test_on_gabors_different_area_contour_plot.py
#python mae_test_on_gabors_different_area_contour_plot_aim.py
#python mae_test_on_gabors_different_L_b_contour_plot.py
#python mae_test_on_gabors_different_L_b_contour_plot_aim.py
#python mae_test_on_gabors_different_rho_contour_plot.py
#python mae_test_on_gabors_different_rho_contour_plot_aim.py
#python mae_test_on_gabors_different_rho_contour_plot_RG.py
#python mae_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python mae_test_on_gabors_different_rho_contour_plot_YV.py
#python mae_test_on_gabors_different_rho_contour_plot_YV_aim.py
#
#python stlpips_test_on_gabors_different_area_contour_plot.py
#python stlpips_test_on_gabors_different_area_contour_plot_aim.py
#python stlpips_test_on_gabors_different_L_b_contour_plot.py
#python stlpips_test_on_gabors_different_L_b_contour_plot_aim.py
#python stlpips_test_on_gabors_different_rho_contour_plot.py
#python stlpips_test_on_gabors_different_rho_contour_plot_aim.py
#python stlpips_test_on_gabors_different_rho_contour_plot_RG.py
#python stlpips_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python stlpips_test_on_gabors_different_rho_contour_plot_YV.py
#python stlpips_test_on_gabors_different_rho_contour_plot_YV_aim.py
#
#python vae_test_on_gabors_different_area_contour_plot.py
#python vae_test_on_gabors_different_area_contour_plot_aim.py
#python vae_test_on_gabors_different_L_b_contour_plot.py
#python vae_test_on_gabors_different_L_b_contour_plot_aim.py
#python vae_test_on_gabors_different_rho_contour_plot.py
#python vae_test_on_gabors_different_rho_contour_plot_aim.py
#python vae_test_on_gabors_different_rho_contour_plot_RG.py
#python vae_test_on_gabors_different_rho_contour_plot_RG_aim.py
#python vae_test_on_gabors_different_rho_contour_plot_YV.py
#python vae_test_on_gabors_different_rho_contour_plot_YV_aim.py


#cd /e/Py_codes/LVM_Comparision/Feature_Similarity_paper_report_50/Band_lim_noise_test/test || return
#python baseline_test_on_band_lim_noise_different_rho_contour_plot.py
#python baseline_test_on_band_lim_noise_different_rho_contour_plot_aim.py
#python cvvdp_test_on_band_lim_noise_different_rho_contour_plot.py
#python cvvdp_test_on_band_lim_noise_different_rho_contour_plot_aim.py
#python dino_test_on_band_lim_noise_different_rho_contour_plot.py
#python dino_test_on_band_lim_noise_different_rho_contour_plot_aim.py
#python dinov2_test_on_band_lim_noise_different_rho_contour_plot.py
#python dinov2_test_on_band_lim_noise_different_rho_contour_plot_aim.py
#python lpips_test_on_band_lim_noise_different_rho_contour_plot.py
#python lpips_test_on_band_lim_noise_different_rho_contour_plot_aim.py
#python mae_test_on_band_lim_noise_different_rho_contour_plot.py
#python mae_test_on_band_lim_noise_different_rho_contour_plot_aim.py
#python openclip_test_on_band_lim_noise_different_rho_contour_plot.py
#python openclip_test_on_band_lim_noise_different_rho_contour_plot_aim.py
#python sam2_test_on_band_lim_noise_different_rho_contour_plot.py
#python sam2_test_on_band_lim_noise_different_rho_contour_plot_aim.py
#python sam_test_on_band_lim_noise_different_rho_contour_plot.py
#python sam_test_on_band_lim_noise_different_rho_contour_plot_aim.py
#python stlpips_test_on_band_lim_noise_different_rho_contour_plot.py
#python stlpips_test_on_band_lim_noise_different_rho_contour_plot_aim.py
#python vae_test_on_band_lim_noise_different_rho_contour_plot.py
#python vae_test_on_band_lim_noise_different_rho_contour_plot_aim.py

#cd /e/Py_codes/LVM_Comparision/Feature_Similarity_paper_report_50/Contrast_masking_test/test || return
#python baseline_test_on_contrast_masking_different_c_contour_plot.py
#python baseline_test_on_contrast_masking_different_c_contour_plot_aim.py
#python cvvdp_test_on_contrast_masking_different_c_contour_plot.py
#python cvvdp_test_on_contrast_masking_different_c_contour_plot_aim.py
#python dino_test_on_contrast_masking_different_c_contour_plot.py
#python dino_test_on_contrast_masking_different_c_contour_plot_aim.py
#python dinov2_test_on_contrast_masking_different_c_contour_plot.py
#python dinov2_test_on_contrast_masking_different_c_contour_plot_aim.py
#python lpips_test_on_contrast_masking_different_c_contour_plot.py
#python lpips_test_on_contrast_masking_different_c_contour_plot_aim.py
#python mae_test_on_contrast_masking_different_c_contour_plot.py
#python mae_test_on_contrast_masking_different_c_contour_plot_aim.py
#python openclip_test_on_contrast_masking_different_c_contour_plot.py
#python openclip_test_on_contrast_masking_different_c_contour_plot_aim.py
#python sam2_test_on_contrast_masking_different_c_contour_plot.py
#python sam2_test_on_contrast_masking_different_c_contour_plot_aim.py
#python sam_test_on_contrast_masking_different_c_contour_plot.py
#python sam_test_on_contrast_masking_different_c_contour_plot_aim.py
#python stlpips_test_on_contrast_masking_different_c_contour_plot.py
#python stlpips_test_on_contrast_masking_different_c_contour_plot_aim.py
#python vae_test_on_contrast_masking_different_c_contour_plot.py
#python vae_test_on_contrast_masking_different_c_contour_plot_aim.py

#cd /e/Py_codes/LVM_Comparision/Feature_Similarity_paper_report_50/Contrast_masking_test_gabor_on_noise/test || return
#python baseline_test_on_contrast_masking_different_c_contour_plot.py
#python baseline_test_on_contrast_masking_different_c_contour_plot_aim.py
#python cvvdp_test_on_contrast_masking_different_c_contour_plot.py
#python cvvdp_test_on_contrast_masking_different_c_contour_plot_aim.py
#python dino_test_on_contrast_masking_different_c_contour_plot.py
#python dino_test_on_contrast_masking_different_c_contour_plot_aim.py
#python dinov2_test_on_contrast_masking_different_c_contour_plot.py
#python dinov2_test_on_contrast_masking_different_c_contour_plot_aim.py
#python lpips_test_on_contrast_masking_different_c_contour_plot.py
#python lpips_test_on_contrast_masking_different_c_contour_plot_aim.py
#python mae_test_on_contrast_masking_different_c_contour_plot.py
#python mae_test_on_contrast_masking_different_c_contour_plot_aim.py
#python openclip_test_on_contrast_masking_different_c_contour_plot.py
#python openclip_test_on_contrast_masking_different_c_contour_plot_aim.py
#python sam2_test_on_contrast_masking_different_c_contour_plot.py
#python sam2_test_on_contrast_masking_different_c_contour_plot_aim.py
#python sam_test_on_contrast_masking_different_c_contour_plot.py
#python sam_test_on_contrast_masking_different_c_contour_plot_aim.py
#python stlpips_test_on_contrast_masking_different_c_contour_plot.py
#python stlpips_test_on_contrast_masking_different_c_contour_plot_aim.py
#python vae_test_on_contrast_masking_different_c_contour_plot.py
#python vae_test_on_contrast_masking_different_c_contour_plot_aim.py